# Generated by Django 6.0.4 on 2026-04-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prefix', models.CharField(default='Providing', max_length=100)),
                ('gradient_text_1', models.CharField(default='the best', max_length=100)),
                ('title_middle', models.CharField(default='Project', max_length=100)),
                ('gradient_text_2', models.CharField(default='Experience', max_length=100)),
                ('description', models.TextField()),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='hero/')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='background/')),
            ],
            options={
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
